README.md
app/controllers/addresses_controller.rb
app/controllers/brands_controller.rb
app/controllers/categories_controller.rb
app/controllers/comments_controller.rb
app/controllers/credits_controller.rb
app/controllers/likes_controller.rb
app/controllers/product_images_controller.rb
app/models/address.rb
app/models/brand.rb
app/models/category.rb
app/models/comment.rb
app/models/credit.rb
app/models/like.rb
app/models/product.rb
app/models/product_image.rb
app/models/user.rb
config/routes.rb
db/migrate/20190724045443_create_addresses.rb
db/migrate/20190724050921_create_credits.rb
db/migrate/20190724051901_create_products.rb
db/migrate/20190724053442_create_categories.rb
db/migrate/20190724054136_create_brands.rb
db/migrate/20190724055115_add_category_to_products.rb
db/migrate/20190724060321_create_product_images.rb
db/migrate/20190724060525_create_likes.rb
db/migrate/20190724060741_create_comments.rb
db/migrate/20190724061004_add_name_to_users.rb
db/schema.rb

コントローラー、モデル、データベースの作成およびルーディングの編集

Meke controller

---

app/assets/stylesheets/registration_top.scss
app/controllers/users_controller.rb
app/views/users/registration_top.html.haml
config/routes.rb

新規会員登録画面作成

---

app/assets/stylesheets/registration-footer.scss
app/assets/stylesheets/registration-haeder.scss
app/views/layouts/_registration.footer.html.haml
app/views/layouts/_registration.header.html.haml

registrasion-kaneko

---

app/assets/stylesheets/application.scss

delete @import "registration/new_member";

change-application.css

---

app/controllers/application_controller.rb
config/deploy/production.rb

#what
BASIC認証追加
#why
本番環境を守るため

add: basic-authentication

---

app/assets/stylesheets/shared/_main_footer.scss
app/assets/stylesheets/shared/_main_sidebar.scss
app/assets/stylesheets/user/_logout.scss
app/views/shared/_main_sidebar.html.haml
app/views/users/logout.html.haml

サイドバーのhover時の色の変更。
ログアウトボタンが文字の部分しかリンクになっていなかったため、ボタン全体がリンクになるよう変更した。
ユーザーがより直感的に利用できるようにするため。

サイドバーのCSS変更

---

app/controllers/application_controller.rb
config/deploy/production.rb

change: besic認証

---

app/controllers/application_controller.rb
config/deploy/production.rb

Reverts kaneko-ryota/freemarket_sample_55-a#52

Revert "change: besic認証"

---

app/assets/stylesheets/shared/_main_footer.scss
app/views/shared/_main_footer.html.haml

what 
reparie footer
why
improve userbility

Nakayama work7

---

app/controllers/application_controller.rb

＃what
Basic認証の設定
＃why
本番環境を守るため

fix-Basic認証

---

app/assets/javascripts/main_header.js
app/assets/stylesheets/shared/_main_header.scss
app/models/product.rb
app/views/products/index.html.haml
app/views/shared/_main_header.html.haml

ヘッダーのホバー時のカテゴリーとブランド一覧を作成した
#Why
ホバー時に一覧が表示されることでユーザーが使いやすくなる。

ヘッダーのカテゴリー、ブランド一覧作成

---

app/assets/stylesheets/products/_detail.scss
app/assets/stylesheets/products/_product_state.scss
app/controllers/products_controller.rb
app/views/products/_product_state.html.haml

what
商品の編集、更新、削除をできるようにした
why
ユーザビリティ向上のため

商品の編集、更新、削除

---

Gemfile
README.md
app/controllers/credits_controller.rb
app/controllers/products_controller.rb
app/controllers/signup_controller.rb
app/views/credits/new.html.haml
app/views/products/purchase_confirmation.html.haml
app/views/shared/_main_sidebar.html.haml
app/views/signup/credit.html.haml
config/breadcrumbs.rb
config/routes.rb
db/schema.rb

商品購入時に、Payjpを利用して料金が支払われるようにした。
メルカリサーバーよりセキュリティの高いサーバーでデータの管理を行えるため

Purchase product

---

app/controllers/users_controller.rb
app/views/shared/_main_sidebar.html.haml
app/views/users/profile.html.haml
app/views/users/show.html.haml
config/routes.rb
db/schema.rb

#what
プロフィール編集
#why
ユーザーが自由で名前や自己紹介するため
Co-Authored-By: Masato Kaneko <kaneko@users.noreply.github.com>

add: profile

---

app/views/shared/_main_sidebar.html.haml
config/initializers/carrierwave.rb
db/schema.rb

#what
S3認証修正
#why
本番環境の画像保存の分離

fix: S3_carrierwave

---

app/assets/stylesheets/products/_detail.scss
app/assets/stylesheets/products/_top_page.scss
app/views/products/index.html.haml
app/views/products/show.html.haml
app/views/shared/_item_box.html.haml
db/schema.rb

トップページのビューを修正した
アイテムボックスから金額部分だけはみ出ており、ビューが崩れていたため修正した。

トップページのビューの修正

---

app/controllers/products_controller.rb
app/views/products/purchase_confirmation.html.haml
app/views/products/show.html.haml

商品詳細の画像のとこ

---

app/assets/stylesheets/products/_sell.scss

商品出品ページの投稿した画像のサイズを修正した。
画像のサイズによってビューが崩れていたため。

商品出品ページ　画像のサイズ修正

---

app/assets/javascripts/product_new.js
app/assets/stylesheets/products/_sell.scss
app/models/product.rb
app/models/product_image.rb
app/views/products/new.html.haml
db/migrate/20190812100413_change_image_of_product_image.rb
db/schema.rb

商品出品の際にバリデーションがかかるようにした。
誤った商品が出品されないようにするため。

商品出品ページのバリデーション

---

app/controllers/signup_controller.rb
db/schema.rb

電話番号認証を本番環境で使得るように変更

---

app/assets/javascripts/flash.js
app/assets/stylesheets/user/_profile.scss
app/controllers/users_controller.rb

フラッシュメッセージを作成した。
更新等をした時にわかりやすくするため。

フラッシュメッセージの作成

---

app/controllers/users/sessions_controller.rb
config/locales/devise.ja.yml

ログインした時に強制的に表示されるフラッシュメッセージを削除しました。

delete session flash message

---

app/views/products/index.html.haml
app/views/products/show.html.haml
app/views/users/show.html.haml

非ログイン時にも商品詳細を見れるように変更しました。不適切なリンクを削除しました。

fix product index

---

app/assets/stylesheets/adresses/_address.scss
app/controllers/application_controller.rb

#what
発送元・お届け先住所入力のサイドバー下部margin
検索結果一覧数を24に変更

fix: margin&24

---

app/views/products/show.html.haml

コメントの数が０の場合、コメント欄が表示されないようにした。
コメントの数が０の時、不必要な枠が存在していたため。

コメント欄の表示・非表示

---

app/views/products/show.html.haml

comment-submit-button comment-button-te

---

app/assets/stylesheets/products/_detail.scss
app/views/products/show.html.haml

#what
サイドバーmargin
コメント欄
＃why
サイドバー下部margin削除
コメント欄条件分岐

fix:comment-submit-button

---

app/assets/stylesheets/products/_search.scss
app/views/products/search.html.haml

検索結果のキーワード表示変更

---

app/controllers/signup_controller.rb
app/views/shared/_main_footer.html.haml

mergemaster
